# Generated by Django 3.2.3 on 2021-11-08 20:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('eee', 'EEE'), ('textile', 'TEXTILE')], default='cse', max_length=8)),
                ('batch_No', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('student_Id', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('staff_user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('course_1', models.CharField(max_length=60)),
                ('courses_2', models.CharField(max_length=60)),
                ('courses_3', models.CharField(max_length=60)),
                ('courses_4', models.CharField(max_length=60)),
                ('courses_5', models.CharField(blank=True, max_length=60, null=True)),
                ('courses_6', models.CharField(blank=True, max_length=60, null=True)),
                ('courses_7', models.CharField(blank=True, max_length=60, null=True)),
                ('courses_8', models.CharField(blank=True, max_length=60, null=True)),
                ('courses_9', models.CharField(blank=True, max_length=60, null=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iems_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('admin_user', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
