# Generated by Django 4.0 on 2021-12-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iems_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='user',
        ),
    ]
