# Generated by Django 3.2.9 on 2021-12-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iems_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='approvedBy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iems_app.batchcounselor'),
        ),
    ]
