# Generated by Django 3.2.9 on 2021-12-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iems_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='designation',
        ),
        migrations.AddField(
            model_name='faculty',
            name='facultyName',
            field=models.CharField(choices=[('cse', 'CSE'), ('eee', 'EEE'), ('textile', 'TEXTILE'), ('bba', 'BBA')], default='cse', max_length=64),
        ),
    ]
