# Generated by Django 4.0 on 2021-12-20 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iems_app', '0002_remove_semester_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iems_app.batchcounselor'),
        ),
    ]
