# Generated by Django 4.0 on 2021-12-20 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iems_app', '0003_alter_courseregistration_approvedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchcounselor',
            name='user',
        ),
        migrations.AddField(
            model_name='batchcounselor',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iems_app.teacher'),
            preserve_default=False,
        ),
    ]
