# Generated by Django 3.2.9 on 2021-12-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iems_app', '0004_remove_batchcounselor_user_batchcounselor_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=128)),
                ('semester', models.CharField(max_length=128)),
                ('batch', models.CharField(max_length=16)),
                ('dayOfWeek', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='Wednesday', max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iems_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iems_app.routine')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iems_app.student')),
                ('takenBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iems_app.teacher')),
            ],
        ),
    ]
