# Generated by Django 4.0 on 2021-12-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iems_app', '0007_attendance_delete_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='routine',
        ),
    ]
